### ISSUE TITLE
Observaciones sobre carga y consulta

### ISSUE THREAD

**Issue by fabiancanuti** [gabriel-tandil/PatoGIS#25]
a - Sería interesante que las especies aparezcan por orden alfabético o al menos que brinde la opción. Eso ayudaría a encontrarlas y mejoraría las posibilidades que brinda el texto predictivo.
 b - Algunas están en mayúsculas y otras no.
 c - No quise probar para no hacer lío, pero aparentemente los reportes de otros usuarios se pueden editar.
 d - En la opción de ver informes de observaciones, solamente aparecen especie y cantidad. ¿Podría agregarse el resto de la información? Laguna, matriz productiva, clima, etc

**Comment by gabriel-tandil** [comment]
@fabiancanuti gracias por los comentarios y sugerencias, contesto tus preguntas/sugerencias:

a - Actualmente se ordena por mas cargados, pero si, es una mejora interesante permitirle al usuario elegir el orden.  Creo ticket #27
b - esto es porque esta permitida la opcion de que cargue cualquier usuario y no hay mucho control actualmente, en algun momento se mejorará y corregiran las existentes.
c - Sí, se puede, cuando se continue el desarrollo es una de las primeras cosas a corregir. Igualmente hay una auditoria que guarda todos los cambios por seguridad. Creo ticket #26
d - No se si esta funcionalidad va a seguir existiendo en el futuro, supongo que se va a fusionar con la de ver/editar observaciones
